# Generated by Django 2.2.7 on 2020-02-27 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0009_auto_20200225_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='physicianclinicworkingtime',
            name='physician_working_branch',
            field=models.CharField(db_column='Adress', default=django.utils.timezone.now, max_length=360),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='physicianhospitalworkingtime',
            name='physician_working_branch',
            field=models.CharField(db_column='Adress', default=django.utils.timezone.now, max_length=360),
            preserve_default=False,
        ),
    ]
