# Generated by Django 2.2.7 on 2020-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0010_auto_20200227_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicianclinicworkingtime',
            name='physician_working_branch',
            field=models.CharField(db_column='physician_working_branch', max_length=360),
        ),
        migrations.AlterField(
            model_name='physicianhospitalworkingtime',
            name='physician_working_branch',
            field=models.CharField(db_column='physician_working_branch', max_length=360),
        ),
    ]
