# Generated by Django 2.2.7 on 2020-03-04 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpanel', '0011_auto_20200227_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='physicianclinicworkingtime',
            name='physician_working_branch',
        ),
        migrations.RemoveField(
            model_name='physicianhospitalworkingtime',
            name='physician_working_branch',
        ),
    ]
